name: Build and Release RPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release RPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up RPM build environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install RPM build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm git ssh

      - name: Build RPM package
        run: |
          echo ${GITHUB_WORKSPACE}
          rpmbuild -ba ${GITHUB_WORKSPACE}/nvidia-exec.spec

      - name: Upload to notRPM
        run: |
          sshpass -p ${secrets.UPLOADERPW} scp -o StrictHostKeyChecking=no ${GITHUB_WORKSPACE}/nvidia-exec.rpm ${secrets.UPLOADERUS}@${secrets.UPLOADERURL}:/var/www/html/notrpm/nvidia-exec.rpm
